global:
  edition: ce
  hosts:
    domain: localhost
    externalIP: 127.0.0.1
  ingress:
    configureCertmanager: false
gitlab-runner:
  install: false
installCertmanager: false
  #nginx-ingress:
  #enabled: true

